In [2]:
import numpy as np

__Задача №1__

Напишите функцию, которая находит сумму четных элементов на главной 
диагонали квадратной матрицы (именно чётных элементов, а не элементов на чётных позициях!). 
Если чётных элементов нет, то вывести 0

In [56]:
arr = np.random.randint(0, 3, (10, 10));
print(arr)

def main_even_sum(array: arr): 
    """ функция находит сумму четных элементов на главной диагонали квадратной матрицы """
    main = np.diagonal(arr)
    main_even = main[ main % 2 == 0]
    summa = sum(main_even)
    return summa

sample = main_even_sum(arr)
print(sample)

[[1 0 1 1 0 2 0 1 2 0]
 [1 1 2 1 2 2 1 0 1 2]
 [0 1 2 1 0 1 0 0 0 1]
 [2 2 0 0 1 2 2 1 1 1]
 [0 2 1 1 2 1 1 2 0 2]
 [1 1 2 2 1 0 2 0 1 2]
 [1 0 2 1 0 0 2 2 0 2]
 [1 0 1 2 2 0 2 1 1 0]
 [0 0 0 1 2 1 2 1 2 1]
 [2 2 1 0 2 2 0 1 2 1]]
8


__Задача №2__

Решить задачи при условии, что массив может быть любой размерности:

2.1 Заменить максимальный элемент массива на 1000. (Повторяющихся максимальных элементов нет. Нужно создать такой 2d массив.)    
2.2 Заменить минимальный элемент массива на 0. (Повторяющиеся минимальные элементы есть, поэтому нужно заменить все)

In [57]:
mas = np.random.randint(1, 15, 10)
print(mas)
nnp.unique(mas, return_counts=True)

[ 1 12  5 12  2  3 12  8 12  9]


(array([ 1,  2,  3,  5,  8,  9, 12]),
 array([1, 1, 1, 1, 1, 1, 4], dtype=int64))

__Задача №3*__  

С помощью numpy написать функцию для кодирования массива (Run-length encoding). 
Все подряд повторения элементов функция сжимает в один элемент и 
считает количество повторений. 
Функция возвращает кортеж из двух `numpy`-векторов одинаковой длины. 
Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: 
```
In[1]: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) 
Out[1]: (np.array([1, 2, 3, 1, 5, 2, 3]), np.array([1, 2, 2, 2, 2, 1, 2]))
```

In [ ]:
# Ваш код 
# Подсказка, что использовать:
# diff() nonzero() where()