In [2]:
# 1. Импортировать NumPy 
import numpy as np

In [45]:
# 1.1 Создать массив 10 x 10 со случайными значениями от 1 до 100(int64)
arr = np.random.randint(1, 100, (10,10), dtype=np.int64)
print(arr, '\n')

# 1.2 найти среднее значение всех элементов массива np.mean()
arr_mean_all = np.mean(arr)
print(arr_mean_all)

# 1.3 найти среднее значение всех элементов для каждой строки   np.mean()
arr_mean = np.mean(arr, axis = 0)

# и добавить как новый столбец (# 1-я ось - это столбцы 2х мерном массиве)
arr_mean = arr_mean.reshape(10,1); arr_mean

new_arr = np.append(arr, arr_mean, axis=1) # 1-я ось - это столбцы 2х мерном массиве
inf = new_arr.shape
print(new_arr, '\n', inf)

arr_mean_all2 = np.mean(new_arr) # ? Не считает новый столбец!!!
print(arr_mean_all2)

# 1.4 найти сумму значение всех элементов для каждого столбца   np.sum()
arr_sum = np.sum(new_arr, axis=1)
inf2 = arr_sum.shape
print(arr_sum, '\n', inf2)

# и добавить как новую строку, учитывая результат 1.3
arr_sum = arr_sum.reshape(1,-1)
print(arr_sum)
new_arr_sum = np.append(arr, arr_sum, axis=0)
print(new_arr_sum)

[[73 91 35 78 41 65 40 39 71 93]
 [51 50 39 73 84 48 99 84 92 35]
 [88 99 16 37 55 45 43 17 40 16]
 [61 38 85 17 35 99 12  2 74 81]
 [64 24 52 48 40 57  5  6 64  6]
 [40 11 79 88 11 95 23 43 15 44]
 [80 73 61 58 87 29 83  3 38 15]
 [55 74 94  2 71 98 59 91 56 39]
 [49 52 13 75 89 26 20 71 91 70]
 [74 92 79  1 41 68 22 35 39  1]] 

52.3
[[73.  91.  35.  78.  41.  65.  40.  39.  71.  93.  63.5]
 [51.  50.  39.  73.  84.  48.  99.  84.  92.  35.  60.4]
 [88.  99.  16.  37.  55.  45.  43.  17.  40.  16.  55.3]
 [61.  38.  85.  17.  35.  99.  12.   2.  74.  81.  47.7]
 [64.  24.  52.  48.  40.  57.   5.   6.  64.   6.  55.4]
 [40.  11.  79.  88.  11.  95.  23.  43.  15.  44.  63. ]
 [80.  73.  61.  58.  87.  29.  83.   3.  38.  15.  40.6]
 [55.  74.  94.   2.  71.  98.  59.  91.  56.  39.  39.1]
 [49.  52.  13.  75.  89.  26.  20.  71.  91.  70.  58. ]
 [74.  92.  79.   1.  41.  68.  22.  35.  39.   1.  40. ]] 
 (10, 11)
52.3
[689.5 715.4 511.3 551.7 421.4 512.  567.6 678.1 614.  492. ] 
 (

In [42]:
# 2. Создать матрицу 7x7 с значениями 1,2,3,4,5,6,7 по главной диагонали, остальные нули.
#    С помощью функции np.diag() и без(используя broadcasting)
d = np.array([1,2,3,4,5,6,7])
r = np.diag(d_arr_new)
print(r)

[[1 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 5 0 0]
 [0 0 0 0 0 6 0]
 [0 0 0 0 0 0 7]]


In [51]:
# 3. Создать случайную матрицу 5x7 целых чисел от 1 до 100 и поменять местами 3 и 5 колонки
arr = np.random.randint(1, 100, (5, 7))
print(arr, '\n')
third = arr[:,2]
print(third)
fiv = arr[:,4]
print(fiv)
arr[:,2] = third
arr[:,4] = fiv
print(arr)

[[44 73 82 33 28 88 13]
 [81 57 14 96 27 58  1]
 [77 62 19 52 75 45 34]
 [ 2 37 32 65 68 39 40]
 [93 31 74 34 74 28  9]] 

[82 14 19 32 74]
[28 27 75 68 74]
[[44 73 82 33 28 88 13]
 [81 57 14 96 27 58  1]
 [77 62 19 52 75 45 34]
 [ 2 37 32 65 68 39 40]
 [93 31 74 34 74 28  9]]
