Задача 2
np.random.seed(5)  
Дана матрица 4х3, со случайные целыми числами от 1 до 100:

найти столбец в котором разница между мин и макс минимальна и удалить его

In [2]:
# Подсказки, что потребуется 
import numpy as np
a2d = np.random.randint(1, 100, (4, 3))
diff = np.max(a2d, axis=0) - np.min(a2d, axis=0) 
print(a2d, '\n\n', diff)
min_el = np.argmin(diff) # flat индекс минимального элемента
print(min_el)

new_a2d = np.delete(a2d, min_el, axis = 1)
print(new_a2d)

[[ 2  7 61]
 [48 50 15]
 [23 17 58]
 [69 84 57]] 

 [67 77 46]
2
[[ 2  7]
 [48 50]
 [23 17]
 [69 84]]


In [ ]:
# Подсказки, что потребуется:
# индекс в размерности массива
np.unravel_index(np.argmin(a2d), a2d.shape)

Задача 3. Решить задачу 2 для 3d массива
Дополнение: вырезать прямоугольник, в котором находится нужный столбец, в глубину

In [3]:
np.random.seed(555)
# a3d = np.random.randint(1, 100, (4, 3, 4))

In [21]:
ax_0 = np.min(a3d, axis=0) # по глубине
ax_1 = np.min(a3d, axis=1) # по строкам
ax_2 = np.min(a3d, axis=2) # по столбцам 
